
services:

  hurl-tests:
    image: ghcr.io/Orange-OpenSource/hurl:7.0.0
    container_name: hurl_runner
    volumes:
      - ./tests:/tests
    working_dir: /tests
    depends_on:
      app:
        condition: service_healthy
    entrypoint: [ "sh", "-c", "hurl --test --continue-on-error *.hurl" ]