name: "home_and_garden"
services:
  db:
    image: postgres
    restart: "unless-stopped"
    environment:
      POSTGRES_DB: "home_and_garden"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d home_and_garden" ]
      interval: 5s
      retries: 5
      start_period: 10s

  app:
    image: ghcr.io/yuliavladimirov/home-and-garden-demo
    restart: "unless-stopped"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/home_and_garden
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./secret.properties:/app/secret.properties
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "http://localhost:8080/manage/health" ]
      interval: 10s
      retries: 10
      start_period: 60s
